### ISSUE TITLE
Compile error with Fable >=5.5.0

### ISSUE THREAD

**Issue by roboz0r** [roboz0r/XParsec#14]
Compiling with 5.5.0+ results in the following errors when running `npm run test`

```
.\src\XParsec\OperatorParsing.fs(315,31): (315,38) error FABLE: The value 'failure' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
.\src\XParsec\OperatorParsing.fs(315,52): (315,59) error FABLE: The value 'failure' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
.\src\XParsec\OperatorParsing.fs(321,31): (321,38) error FABLE: The value 'failure' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
.\src\XParsec\OperatorParsing.fs(326,31): (326,38) error FABLE: The value 'failure' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
.\src\XParsec\OperatorParsing.fs(316,40): (316,47) error FABLE: The value 'failure' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
.\src\XParsec\OperatorParsing.fs(321,66): (321,73) error FABLE: The value 'failure' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
.\src\XParsec\OperatorParsing.fs(326,66): (326,73) error FABLE: The value 'failure' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
.\src\XParsec\OperatorParsing.fs(327,46): (327,53) error FABLE: The value 'failure' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
.\src\XParsec\OperatorParsing.fs(377,14): (377,58) error FABLE: The value 'parseLhsInternal' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
.\src\XParsec\OperatorParsing.fs(381,12): (381,95) error FABLE: The value 'parseRhsInternal' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
.\src\XParsec\OperatorParsing.fs(382,27): (382,50) error FABLE: The value 'mergeWithError' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
Compilation failed
```

It appears the issue is caused by https://github.com/fable-compiler/Fable/pull/4701 being too restrictive about inlining. i.e. a private function should be able to inline into another private function in the same module.
